### ISSUE TITLE
Sounds like an authorization issue?

### ISSUE THREAD

**Issue by erxson** [MrLetsplay2003/ShittyAuthServer#12]
I probably did something wrong during the installation, but I can not log into an already created account. It is also strange that after registration you are again asked for a username and password. Any ideas?
Another question, is it possible somehow in the future to translate text or change themes in WebInterfaceAPI without changing the library itself?

https://github.com/MrLetsplay2003/ShittyAuthServer/assets/50082485/08b1781f-08c0-4509-8df9-6c90de7dc1fb

**Comment by MrLetsplay2003** [comment]
This issue was caused by the server not correctly storing user credentials upon registration and should now be fixed.

As for the second username and password, those are the Minecraft account credentials you use for login in the launcher, which are separate from the WebinterfaceAPI account credentials.

Changing themes is possible by creating a custom CSS file in the `include/css/theme` folder (just copy one of the existing ones and change the colors, then set the Theme setting to the name of your new file without the `.css`), translation is however not currently possible.

**Comment by erxson** [comment]
Thank you for quick response!

**Comment by erxson** [comment]
By the way, have you updated the jar file on your maven repository?

**Comment by MrLetsplay2003** [comment]
Yes, it should have been rebuilt automatically

**Comment by erxson** [comment]
Ok. Thank you!
